# fly.toml app configuration file generated for tls-proxy on 2025-03-16T17:50:42-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tls-proxy'
primary_region = 'sjc'

[build]
  dockerfile = 'Dockerfile'
  build-target = 'runner'

  [build.args]
    PLATFORM = 'linux/amd64'

[[services]]
  protocol = 'tcp'
  internal_port = 8080
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [[services.ports]]
    port = 443
    handlers = ['tls']

    [services.ports.tls_options]
      alpn = ['h2', 'http/1.1']
      versions = ['TLSv1.2', 'TLSv1.3']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
